name: CI Pipeline - Security

on:
  push:
    paths:
      - '03-security-and-secrets/**'
    branches:
      - main
      - dev

jobs:
  security-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 03-security-and-secrets

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t cicd-secure .

      
      - name: Set Secret
        run: echo "API_KEY=my-super-secret-key" >> $GITHUB_ENV

      - name: Run Container
        run: docker run -d -p 5000:5000 \
          -e API_KEY=$API_KEY \
          --name prod-container cicd-secure

      - name: Wait for App (Fail if not ready)
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:5000; then
              echo "App is up!"
              exit 0
            fi
            echo "Waiting for app...."
            sleep 2
          done

          echo "App failed to start"
          exit 1

      # 💣 SECRET LEAK
      - name: Show Logs
        run: docker logs prod-container

      - name: Cleanup
        if: always()
        run: docker stop prod-container && docker rm prod-container